apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-repo:latest
        ports:
        - containerPort: 8080
